### PR TITLE
Feature/finish

### PR DESCRIPTION
**Pull request by MarcinK50**
# Finnaly, I Finished!!!

## Features:
- lookup grades
- join to online lessons
- read school announcements
- send, delete and read messages
- and MANY MANY MORE
<p align="center">
this slowpoke moves
</p>

### CODE REVIEW

**Comment by Pengwius** [comment]
Rick rolled :/

**Comment by Pengwius** [comment]
Sorry, but I can't approve this

**Comment by MarcinK50** [comment]
> 
> 
> Sorry, but I can't approve this

merguj i to już

**Review by Zaptyp — CHANGES_REQUESTED** [review]
Access Denied. Nie troluj

**Review by MarcinK50 — COMMENTED** [review]
weri grejt

**Comment by Zaptyp** [comment]
Został zamknięty z powodu robienia trolli w pliku README.md

**Review by Pengwius — COMMENTED** [review]
😕

**Comment by MarcinK50** [comment]
Pozwólcie że usunę ten żart, już 22 maja :/

**Pull request closed without merging**
